### ISSUE TITLE
Recent Posts Needed

### ISSUE THREAD

**Issue by eddiewillers** [pow-co/powco.dev#10]
I create a GitHub issue. 

Then I want to boost it.

But where is it?

I go to Powco.Dev and scroll down and down and down past hundreds of issues.

Is it here? Where can I find it?

Maybe it would be helpful for people using this app if there were a "Recent Posts" section so that a user could go to Powco.Dev, find the latest post, and boost it.

It would help me a lot! Thanks in advance to anyone who can help me with this. 

**I am staking 1 POWCO worth absolutely zero ($0.00000000) onto this job for its completion.**

**I also stake 10 ASK worth absolutely zero ($0.00000000) as another token of my appreciation.**

If anyone else wants this done, I encourage you to add to the stake for this job with a comment below, to be awarded on the honor system to the man, woman, machine who completes this for us.

**Comment by owenkellogg** [comment]
> @owenkellogg please push latest build live and then I'll look into it

Pushed!
