### ISSUE TITLE
Sorting by Tags Needed

### ISSUE THREAD

**Issue by eddiewillers** [pow-co/powco.dev#11]
It appears that Powco.Dev intends to offer sorting by tags or organization.

However, when I click on a tag, for example "powco.dev" the URL changes but the results displayed are the same -- not filtered. 

Example:

![Screenshot_20221207-135810_Brave.jpg](https://user-images.githubusercontent.com/4019818/206185710-16ceadf9-92d7-41d7-9c45-4858b0222d48.jpg)

**Comment by GuiDeMa** [comment]
Idk filtering by repo looks fine to me 
https://powco.dev/org/pow-co/powco.dev

**Comment by eddiewillers** [comment]
Yes this is now resolved. Thank you.
