### ISSUE TITLE
[BUG] "Dependabot" Makes Powco.dev Unusable!

### ISSUE THREAD

**Issue by eddiewillers** [pow-co/powco.dev#22]
I went to Powco.dev to Boost an Issue that I recently created, but I could not find it anywhere because there were a ton of really long posts by Dependabot in the way!

It would be better if these posts were hidden.

See video below for example of this bug:

https://user-images.githubusercontent.com/4019818/208151633-14536184-be6b-4e89-99c3-e36c87dd6d10.mp4

**Comment by owenkellogg** [comment]
guidema pushed a fix

**Comment by eddiewillers** [comment]
:100: :1st_place_medal: @GuiDeMa
