### ISSUE TITLE
Automatic replies to issues on github when they appear on powco.dev

### ISSUE THREAD

**Issue by DanielKrawisz** [pow-co/powco.dev#28]
A bot should make a reply to an issue on github to link us to the post on powco.dev, possibly even provide a boost button or link on github if that is possible and should report the bounty address for the issue as discussed at https://github.com/pow-co/powco.dev/issues/8

**Comment by owenkellogg** [comment]
Very good idea this will streamline the our process significantly.

**Comment by owenkellogg** [comment]
This is in progress. @DanielKrawisz Please test creating an issue and see how the automatic reply works.

**Comment by DanielKrawisz** [comment]
works great!
