### ISSUE TITLE
Tuning Panel Should Default to Week

### ISSUE THREAD

**Issue by eddiewillers** [pow-co/powco.dev#6]
Currently, the default for Powco.dev is set to:  "All"

The result is that when a user goes to Powco.dev, he sees issues at the top which are old and irrelevant. For example, the top three issues at the top of Powco.dev right now are all resolved. This makes it harder to find relevant issues. 

Instead, if the default was set to "Week" that would give users a much more relevant set of results to sort by, since issues that are top boosted within the past 7 days are likely still relevant.

**Comment by GuiDeMa** [comment]
Tuning panel defaults to whatever you want. It keeps in memory user selection
