### ISSUE TITLE
Tuning Panel Currently Inoperable

### ISSUE THREAD

**Issue by eddiewillers** [pow-co/powco.dev#7]
Currently, when a user clicks the Tuning Panel to sort issues on Powco.dev by time period, the results are unchanged.

It is important that a user can narrow his search down to see only the top most boosted content today so that we know what is truly the most painful issue that needs solving most immediately.

**Comment by owenkellogg** [comment]
boostdat

**Comment by GuiDeMa** [comment]
Seems fixed can you confirm ?
